name: Mounts
version: '1.0-SNAPSHOT'
main: co.killionrevival.mc.Mounts
api-version: '1.21'
authors: [ Evan J ]
commands:
  mountegg:
    description: "Get a mount egg"
    usage: "/mountegg [player]"
    permissions: mounts.admin
  mounteggedit:
    description: "Add/Edit mount egg attributes"
    usage: "/mounteggedit <attribute> <decimal value | unset>"
    permissions: mounts.admin
permissions:
  mounts.admin:
    default: op
  mounts.events.spawn:
    default: op
  mounts.events.spawn.reuse:
    default: op
